### ISSUE TITLE
不支持v5版本的hexo

### ISSUE THREAD

**Issue by ql-isaac** [mythsman/hexo-douban#142]
hexo 版本:v5.4.2

hexo-douban 版本:v2.2.2

douban id :214534818

问题描述:
ERROR {
  err: /home/ubuntu/www/node_modules/hexo-douban/node_modules/urllib/src/cjs/index.js:12
      if (options?.socketPath) {
                  ^
  
  SyntaxError: Unexpected token '.'
      at Module._compile (internal/modules/cjs/loader.js:895:18)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
      at Module.load (internal/modules/cjs/loader.js:815:32)
      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
      at Module.require (internal/modules/cjs/loader.js:852:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/home/ubuntu/www/node_modules/hexo-douban/lib/util.js:4:16)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
      at Module.load (internal/modules/cjs/loader.js:815:32)
      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
      at Module.require (internal/modules/cjs/loader.js:852:19)
      at req (/home/ubuntu/www/node_modules/hexo/lib/hexo/index.js:292:23)
      at /home/ubuntu/www/node_modules/hexo-douban/index.js:5:13
      at /home/ubuntu/www/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/home/ubuntu/www/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/ubuntu/www/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/ubuntu/www/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ubuntu/www/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ubuntu/www/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/ubuntu/www/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/ubuntu/www/node_modules/bluebird/js/release/async.js:86:9)
} Plugin load failed: %s hexo-douban

**Comment by mythsman** [comment]
node 版本是多少？感觉是版本有点问题。。。

**Comment by ql-isaac** [comment]
> 

12.....

**Comment by mythsman** [comment]
hexo v5 + node v12 下urllib的依赖有点问题，要不直接升最新吧。。。🥹

**Comment by ql-isaac** [comment]
> hexo v5 + node v12 下urllib的依赖有点问题，要不直接升最新吧。。。🥹

好的，老大，终于有理由升级了
![1F382D12](https://github.com/mythsman/hexo-douban/assets/53886119/2610d547-0cf4-4d5c-b4d1-4c7bf461e010)
