### ISSUE TITLE
出现接口报错，接口可能已经失效了？不太确定

### ISSUE THREAD

**Issue by NOeSIS-yu** [mythsman/hexo-douban#154]
node 版本:18.16.0

hexo 版本: 6.3

hexo-douban 版本:

douban id : 

问题描述:ERROR
HttpClientRequestTimeoutError: Request timeout for 10000 ms
    at HttpClient._HttpClient_requestInternal (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\HttpClient.js:532:19)
    at async HttpClient.request (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\HttpClient.js:112:16)
    at async Object.request (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\index.js:17:12)
    at async module.exports.syncFetch (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\util.js:28:24)
    at async module.exports.fetchData (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\http.js:221:22)
    at async module.exports (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\generator.js:44:16)
WARN  Cannot connect to server
INFO  0 (wish), 0 (do),0 (collect) movie loaded in 14121 ms
ERROR
HttpClientRequestTimeoutError: Request timeout for 10000 ms
    at HttpClient._HttpClient_requestInternal (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\HttpClient.js:532:19)
    at async HttpClient.request (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\HttpClient.js:112:16)
    at async Object.request (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\index.js:17:12)
    at async module.exports.syncFetch (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\util.js:28:24)
    at async module.exports.fetchData (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\http.js:221:22)
    at async module.exports (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\generator.js:44:16)
WARN  Cannot connect to server
INFO  0 (wish), 0 (do),0 (collect) game loaded in 14125 ms
ERROR
HttpClientRequestTimeoutError: Request timeout for 10000 ms
    at HttpClient._HttpClient_requestInternal (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\HttpClient.js:532:19)
    at async HttpClient.request (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\HttpClient.js:112:16)
    at async Object.request (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\urllib\src\cjs\index.js:17:12)
    at async module.exports.syncFetch (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\util.js:28:24)
    at async module.exports.fetchData (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\http.js:221:22)
    at async module.exports (E:\hexo\hexo-theme-fomalhaut\hexo-theme-Fomalhaut\node_modules\hexo-douban\lib\generator.js:44:16)

**Comment by mythsman** [comment]
服务器网络环境不太好，过一会试试就好😏
