### ISSUE TITLE
生成页面代码报错，且无任何影片信息

### ISSUE THREAD

**Issue by lz732895965** [mythsman/hexo-douban#160]
node 版本:v20.9.0

hexo 版本:7.0.0

hexo-douban 版本:2.2.6

douban id :152666457

问题描述:
在hexo中，使用hexo -g 命令会出现以下错误，实际已生成的页面中无任何影片信息
`JSONResponseFormatError: Unexpected token '<', "<html>
<h"... is not valid JSON (data json format: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.23.3</center>\r\n</body>\r\n</html>\r\n")
    at JSON.parse (<anonymous>)
    at parseJSON (E:\Blogroot\xiaoxiao\node_modules\urllib\dist\commonjs\utils.js:34:21)
    at #requestInternal (E:\Blogroot\xiaoxiao\node_modules\urllib\dist\commonjs\HttpClient.js:525:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.request (E:\Blogroot\xiaoxiao\node_modules\urllib\dist\commonjs\HttpClient.js:107:16)
    at async Object.request (E:\Blogroot\xiaoxiao\node_modules\urllib\dist\commonjs\index.js:25:12)
    at async module.exports.syncFetch (E:\Blogroot\xiaoxiao\node_modules\hexo-douban\lib\util.js:28:24)
    at async module.exports.fetchData (E:\Blogroot\xiaoxiao\node_modules\hexo-douban\lib\http.js:221:22)
    at async module.exports (E:\Blogroot\xiaoxiao\node_modules\hexo-douban\lib\generator.js:44:16)
WARN  Cannot connect to server
INFO  0 (wish), 0 (do),0 (collect) movie loaded in 1974 ms`

**Comment by mythsman** [comment]
别骂了别骂了，服务器放家里，早上小区停电了，晚上下班回家开开就好了。。。

**Comment by lz732895965** [comment]
原来是这样啊，我以为是我的问题呢  谢谢大佬爱的发电

**Comment by promefire** [comment]
我也出现了这个问题，请问如何把爬取服务放在我自己的服务器上呢？

**Comment by mythsman** [comment]
巧了，今天也停电了。。。

**Comment by mythsman** [comment]
> 我也出现了这个问题，请问如何把爬取服务放在我自己的服务器上呢？

可以看下 [mouban](https://github.com/mythsman/mouban) 项目。
