### ISSUE TITLE
idouban读取异常

### ISSUE THREAD

**Issue by itian932** [mythsman/hexo-douban#173]

**Comment by Hoveco** [comment]
Unhandled rejection Error: ENOENT: no such file or directory, open '..\..\idouban\dist\index.js'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at readFileSync (D:\20240527blog\node_modules\hexo-douban\node_modules\hexo-fs\dist\fs.js:235:43)
    at l (D:\20240527blog\node_modules\hexo-douban\dist\index.js:15:376)
    at Hexo.<anonymous> (D:\20240527blog\node_modules\hexo-douban\dist\index.js:15:2397)
    at Hexo.tryCatcher (D:\20240527blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\20240527blog\node_modules\bluebird\js\release\method.js:15:34)
    at D:\20240527blog\node_modules\hexo\lib\hexo\index.js:405:22
    at tryCatcher (D:\20240527blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\20240527blog\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (D:\20240527blog\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (D:\20240527blog\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (D:\20240527blog\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (D:\20240527blog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\20240527blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\20240527blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\20240527blog\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
  

V2.3.1我升级了，有不同的报错

**Comment by mythsman** [comment]
> ENOENT: no such file or directory, open '....

呃呃，好像有个兼容问题，升一下 v2.3.3 🥹
