### ISSUE TITLE
生成页面时报错：Unhandled rejection SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by insectmk** [mythsman/hexo-douban#178]
node 版本: v20.15.0

hexo 版本: 7.3.0

hexo-douban 版本:  2.3.6

douban id : 228725535

问题描述: 之前都没问题，这两天发现执行`hexo douban`时报错，报错内容如下：

```tex
Unhandled rejection SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4306:19)
    at successSteps (node:internal/deps/undici/undici:4288:27)
    at fullyReadBody (node:internal/deps/undici/undici:2724:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:4297:7)
    at async Object.u (D:\Hub\hexo-gitee-blog-management\node_modules\idouban\dist\http.js:1:4547)
    at async u (D:\Hub\hexo-gitee-blog-management\node_modules\hexo-douban\dist\index.js:7:749)
```

**Comment by ABCkillmen** [comment]
我刚刚也是，最后我generator也不行了，直接gg

**Comment by ABCkillmen** [comment]
我是这个
Unhandled rejection SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19)
    at successSteps (node:internal/deps/undici/undici:5555:27)
    at fullyReadBody (node:internal/deps/undici/undici:1665:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5564:7)
    at async Object.u (D:\666\github2\KillAMan\node_modules\idouban\dist\http.js:1:4547)
    at async u (D:\666\github2\KillAMan\node_modules\hexo-douban\dist\index.js:7:749)

**Comment by insectmk** [comment]
@ABCkillmen 可能是豆瓣的接口变了，等作者适配啦

**Comment by ABCkillmen** [comment]
嗯嗯，我现在已经把插件部分注释掉了，要不然其他也无法生成了哈哈

**Comment by brycezhang** [comment]
搜到的这个issue，看起来是服务挂了，等待恢复吧
[生成页面代码报错，且无任何影片信息](https://github.com/mythsman/hexo-douban/issues/160)

**Comment by ABCkillmen** [comment]
我开始还以为是我nodejs问题卸载重装了半天也失败，最后才从我昨天动过的所有东西排查了好几个小时啊啊啊啊最后终于找到问题所在了，我还一行一行检查我每个的配置文件，妈呀



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月08日 18:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mythsman/hexo-douban] 生成页面时报错：Unhandled rejection SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON (Issue #178) |

搜到的这个issue，看起来是服务挂了，等待恢复吧
生成页面代码报错，且无任何影片信息

**Comment by mythsman** [comment]
ddns穿透家里的服务器，不是很稳定，偶尔会挂，各位海涵😊。

**Comment by mythsman** [comment]
https://stats.uptimerobot.com/EBFuSCzWaX
最近稳定性堪忧。。。

**Comment by ABCkillmen** [comment]
问题不大，作者辛苦了hhhh



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月08日 23:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mythsman/hexo-douban] 生成页面时报错：Unhandled rejection SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON (Issue #178) |

Closed #178 as completed.
