### ISSUE TITLE
插件是否和hexo-bilibili-bangumi不兼容

### ISSUE THREAD

**Issue by Adam8en** [mythsman/hexo-douban#180]
node 版本: v18.17.0

hexo 版本:  6.3.0

hexo-douban 版本: 2.3.6

douban id : 283842719

问题描述: 
按照文档配置好运行hexo douban的时候报错如下图
![image](https://github.com/user-attachments/assets/4f5781e1-b937-46a0-990b-26c3265e1ab7)
回显“INFO  44 bangumis have been loaded”，这个数目刚好和我使用hexo-bilibili-bangumi时导入的动漫数量一致。
删除hexo-bilibili-bangumi插件后，信息“INFO  44 bangumis have been loaded”被移除，但仍然回显报错：
Unhandled rejection TypeError: g.actions.filter is not a function
    at u (D:\hexo\node_modules\hexo-douban\dist\index.js:7:291)
    at Hexo.<anonymous> (D:\hexo\node_modules\hexo-douban\dist\index.js:7:2585)
    at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at D:\hexo\node_modules\hexo\lib\hexo\index.js:407:22
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\hexo\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (D:\hexo\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (D:\hexo\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (D:\hexo\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by mythsman** [comment]
似乎是配置不对，看下yaml配置里的 actions 咋配的。

**Comment by Adam8en** [comment]
> 似乎是配置不对，看下yaml配置里的 actions 咋配的。

douban:
  id: 283842719
  builtin: false
  dynamic: false
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  swup: false
  book:
    path: books/index.html
    title: "书籍列表"
    quote: "我思故我在"
    actions: collect
      - do
      - wish
      - collect
    option:

**Comment by mythsman** [comment]
actions: collect

这里的collect干掉，格式不对了。

**Comment by Adam8en** [comment]
> actions: collect
> 
> 这里的collect干掉，格式不对了。

可以了可以了
