### ISSUE TITLE
生成文件时发生错误

### ISSUE THREAD

**Issue by yooceii** [mythsman/hexo-douban#26]
在使用hexo douban生成文件时，出现错误。

以下是命令行输出的信息：
INFO  Start processing
INFO  5 books have been loaded in 754 ms
INFO  45 movies have been loaded in 4327 ms
INFO  0 games have been loaded in 2127 ms
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\common\utils.js [ 45.85% saved]
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\common\animation.js [ 64.76% saved]
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\common\pack.js [ 51.37% saved]
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\layout\loading.js [ 32.61% saved]
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\layout\back-top.js [ 55.25% saved]
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\layout\header.js [ 44.95% saved]
INFO  hexo-filter-cleanup(JS): S:\i.t\blog\yooceii.github.io\themes\hexo-theme-skapp\source\js\layout\post.js [ 48.44% saved]
INFO  hexo-filter-cleanup(USEREF): js/common.js
INFO  hexo-filter-cleanup(HTML): 2018/06/05/hello-world/index.html [ 33.62% saved]
INFO  hexo-filter-cleanup(HTML): books/index.html [ 31.97% saved]
INFO  hexo-filter-cleanup(HTML): movies/index.html [ 23.17% saved]
INFO  hexo-filter-cleanup(HTML): games/index.html [ 35.02% saved]
INFO  hexo-filter-cleanup(HTML): archives/index.html [ 41.51% saved]
INFO  hexo-filter-cleanup(HTML): archives/2018/index.html [ 41.49% saved]
INFO  hexo-filter-cleanup(HTML): archives/2018/06/index.html [ 41.59% saved]
INFO  hexo-filter-cleanup(HTML): index.html [ 40.59% saved]
Unhandled rejection TypeError: self.route.get(...)._data is not a function
    at names.forEach.name (S:\i.t\blog\yooceii.github.io\node_modules\hexo-douban\index.js:83:48)
    at Array.forEach (<anonymous>)
    at S:\i.t\blog\yooceii.github.io\node_modules\hexo-douban\index.js:81:11
    at tryCatcher (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (S:\i.t\blog\yooceii.github.io\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by mythsman** [comment]
你试试看关掉hexo-filter-cleanup那个呢？

**Comment by yooceii** [comment]
关了以后能生成html文件 但是开启hexo服务后进/books这些都是空白的 查看这些index.html都是有内容的。查看这些页面的源码也是有的

**Comment by mythsman** [comment]
有内容为什么是空白呢。。。。这不科学。。。

**Comment by yooceii** [comment]
感觉时跟我这个主题不兼容，在load时需要load /books底下的一些js文件，但这些都是theme的js文件

**Comment by yooceii** [comment]
感觉是跟我这个主题不兼容，在load时需要load /books底下的一些js文件，但这些都是theme的js文件

**Comment by mythsman** [comment]
我这个礼拜在外面旅游。。。下礼拜我来看看吧。。。

**Comment by yooceii** [comment]
嗯 我自己也再debug一下，毕竟hexo和node.js这块还不是太熟

**Comment by mythsman** [comment]
不知楼主问题解决了没有

**Comment by yooceii** [comment]
还没😔 这走事情太多。。 签证体检选课。。

**Comment by mythsman** [comment]
哈哈

**Comment by ericX8** [comment]
楼主解决了吗

**Comment by yooceii** [comment]
> 楼主解决了吗

Sorry啊， 我已经弃坑了😂
